-- AlterTable
ALTER TABLE "CUK" ADD COLUMN     "institutionCode" TEXT;

-- AlterTable
ALTER TABLE "Message" ALTER COLUMN "TSN" DROP NOT NULL,
ALTER COLUMN "OSN" DROP NOT NULL,
ALTER COLUMN "NSE" DROP NOT NULL,
ALTER COLUMN "LSN" DROP NOT NULL,
ALTER COLUMN "NSR" DROP NOT NULL;
