version: "3.8"
services:
  webapp:
    build: .
    image: admin-sinacofi
    container_name: admin-sinacofi
    restart: always
    env_file:
      - .env
    ports:
      - "8080:3000"
    volumes:
      # - ${LOG_PATH:-./logs/}:/var/log
      # - /adjuntos:/adjuntos 
    depends_on:
      - postgres
    command: ["npm", "start"]
