version: "3.8"

services:
  webapp:
    build: .
    image: messages:latest
    container_name: messages
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - /var/logs/containers:/logs
      - /adjuntos:/adjuntos 
    command: ["npm", "start"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 1m30s
      timeout: 10s
      retries: 3
