version: "3.8"
services:
  webapp:
    build: .
    image: messages
    container_name: messages
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      # - ${LOG_PATH:-./logs/}:/var/log
      - /adjuntos:/adjuntos 
    command: ["npm", "start"]
