services:
  messages:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_HOST: ${DB_HOST}
        DB_NAME: ${DB_NAME}
        FILES_PATH: ${FILES_PATH}
        LOG_FILENAME: ${LOG_FILENAME}
        PORT: ${PORT}
        ADMIN_CLIENT_URL: ${ADMIN_CLIENT_URL}
        RULE_CLIENT_URL: ${RULE_CLIENT_URL}
        IDCS_HOST: ${IDCS_HOST}
        IAM_CLIENT_ID: ${IAM_CLIENT_ID}
        IAM_CLIENT_SECRET: ${IAM_CLIENT_SECRET}
        BASE_URL: ${BASE_URL}
    image: messages:latest
    container_name: messages
    restart: always
    env_file:
      - .env
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      ADMIN_CLIENT_URL: ${ADMIN_CLIENT_URL}
      RULE_CLIENT_URL: ${RULE_CLIENT_URL}
      IDCS_HOST: ${IDCS_HOST}
      IAM_CLIENT_ID: ${IAM_CLIENT_ID}
      IAM_CLIENT_SECRET: ${IAM_CLIENT_SECRET}
      BASE_URL: ${BASE_URL}
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:5432/${DB_NAME}
      IAM_SIGN_OUT_URL: ${IDCS_HOST}/oauth2/v1/userlogout
      IAM_BASE_URL: ${IDCS_HOST}/.well-known/openid-configuration
      IAM_AUTHORIZATION_URL: ${IDCS_HOST}/oauth2/v1/authorize
      IAM_VALIDATE_TOKEN_URL: ${IDCS_HOST}/oauth2/v1/token
      IAM_REVOKE_URL: ${IDCS_HOST}/oauth2/v1/revoke
      IAM_JWK_TOKEN_URL: ${IDCS_HOST}/admin/v1/SigningCert/jwk
      NEXTAUTH_URL: ${BASE_URL}:${PORT}
      IAM_REDIRECT_URL: ${BASE_URL}:${PORT}/callback
      PORT: ${PORT}
      LOG_FILENAME: ${LOG_FILENAME}
      FILES_PATH: ${FILES_PATH}   
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ${LOG_FILENAME}:/logs
      - ${FILES_PATH}:/files 
    command: ["npx", "next", "start", "-p", "${PORT}"]
    networks:
      - messages-rules

networks:
  messages-rules:
    external: true