export enum MessageTypes {
    ALZAMIENTO_HIPOTECARIO = "670",
    ACEPTACION_DE_ALZAMIENTO_HIPOTECARIO = "671",
    RECHAZO_DE_ALZAMIENTO_HIPOTECARIO = "672",
    AVISO_DE_CLIENTE_EN_NORMALIZACION = "673",
    SOLICITUD_DE_ALZAMIENTO_HIPOTECARIO = "674",
    LIQUIDACION_DE_PREPAGO_DE_ALZAMIENTO_HIPOTECARIO = "675",
    DATOS_PARA_EL_PAGO_AH = "676",
    AVISO_DE_PAGO_AH = "677",
    RECHAZO_DE_PAGO_AH = "678",
    CONFIRMACION_DE_PAGO_AH = "679",
    TRANSFERENCIA_DE_FONDOS_INDIVIDUAL = "136",
    TEXTO_LIBRE = "199",
}

export enum MessageDescriptions {
    ALZAMIENTO_HIPOTECARIO = "ENVIO ALZAMIENTO HIPOTECARIO",
    EVALUACION_DE_ALZAMIENTO_HIPOTECARIO_EN_PROCESO = "EVALUACION DE ALZAMIENTO HIPOTECARIO EN PROCESO",
    ACEPTACION_DE_ALZAMIENTO_HIPOTECARIO = "ACEPTACION DE ALZAMIENTO HIPOTECARIO",
    RECHAZO_DE_ALZAMIENTO_HIPOTECARIO = "RECHAZO DE ALZAMIENTO HIPOTECARIO",
    SOLICITUD_DE_ALZAMIENTO_HIPOTECARIO = "SOLICITUD DE ALZAMIENTO HIPOTECARIO",
    AVISO_DE_CLIENTE_EN_NORMALIZACION = "AVISO DE CLIENTE EN NORMALIZACION",
    TRANSFERENCIA_DE_FONDOS_INDIVIDUAL = "TRANSFERENCIA DE FONDOS INDIVIDUAL",
    LIQUIDACION_DE_PREPAGO_DE_ALZAMIENTO_HIPOTECARIO = "LIQUIDACION DE PREPAGO DE ALZAMIENTO HIPOTECARIO",
    DATOS_PARA_EL_PAGO_AH = "DATOS PARA EL PAGO AH",
    AVISO_DE_PAGO_AH = "AVISO DE PAGO AH",
    RECHAZO_DE_PAGO_AH = "RECHAZO DE PAGO AH",
    CONFIRMACION_DE_PAGO_AH = "CONFIRMACION DE PAGO AH",
    ESCRITURA_FIRMADA = "ESCRITURA FIRMADA", 
    TEXTO_LIBRE = "TEXTO LIBRE",
}

export const getDescriptionByType = (type: string): string => {
    switch (type) {
        case MessageTypes.ALZAMIENTO_HIPOTECARIO:
            return MessageDescriptions.ALZAMIENTO_HIPOTECARIO;
        case MessageTypes.ACEPTACION_DE_ALZAMIENTO_HIPOTECARIO:
            return MessageDescriptions.ACEPTACION_DE_ALZAMIENTO_HIPOTECARIO;
        case MessageTypes.RECHAZO_DE_ALZAMIENTO_HIPOTECARIO:
            return MessageDescriptions.RECHAZO_DE_ALZAMIENTO_HIPOTECARIO;
        case MessageTypes.AVISO_DE_CLIENTE_EN_NORMALIZACION:
            return MessageDescriptions.AVISO_DE_CLIENTE_EN_NORMALIZACION;
        case MessageTypes.TRANSFERENCIA_DE_FONDOS_INDIVIDUAL:
            return MessageDescriptions.TRANSFERENCIA_DE_FONDOS_INDIVIDUAL;
        case MessageTypes.TEXTO_LIBRE:
            return MessageDescriptions.TEXTO_LIBRE;
        default:
            return '';
    }
}