export enum MessageTypes {
    ALZAMIENTO_HIPOTECARIO = "670",
    ACEPTACION_DE_ALZAMIENTO_HIPOTECARIO = "671",
    RECHAZO_DE_ALZAMIENTO_HIPOTECARIO = "672",
    AVISO_DE_CLIENTE_EN_NORMALIZACION = "673",
    TRANSFERENCIA_DE_FONDOS_INDIVIDUAL = "136",
    TEXTO_LIBRE = "199",
}

export enum MessageDescriptions {
    ALZAMIENTO_HIPOTECARIO = "ALZAMIENTO HIPOTECARIO",
    ACEPTACION_DE_ALZAMIENTO_HIPOTECARIO = "ACEPTACION DE ALZAMIENTO HIPOTECARIO",
    RECHAZO_DE_ALZAMIENTO_HIPOTECARIO = "RECHAZO DE ALZAMIENTO HIPOTECARIO",
    AVISO_DE_CLIENTE_EN_NORMALIZACION = "AVISO DE CLIENTE EN NORMALIZACION",
    TRANSFERENCIA_DE_FONDOS_INDIVIDUAL = "TRANSFERENCIA DE FONDOS INDIVIDUAL",
    TEXTO_LIBRE = "TEXTO LIBRE",
}