/*
 * Copyright (c) 2018 Oracle and/or its affiliates. All rights reserved.
 *
 */

const IDCSConstants = {

    IDCSHost: 'IDCSHost',
    CLIENT_ID: 'ClientId',
    CLIENT_SECRET: 'ClientSecret',
    CLIENT_TENANT: 'ClientTenant',
    AUDIENCE_SERVICE_URL : "AudienceServiceUrl",
    RESOURCE_TENANCY : "ResourceTenancy",
    CROSS_TENANT : "CrossTenant",
    TOKEN_ISSUER : "TokenIssuer",
    CALL_BACK_URL : "CallBackURL",
    USER_SCOPE : "UserScope",
    STATE : "State",
    RESPONSE_TYPE : "ResponseType",
    FAILURE_URL : "FailureURL",
    TOKEN_CLOCK_SKEW : "TokenClockSkew",
    TOKEN_CLOCK_SKEW_DEFAULT_VALUE : 120,
    APP_NAME : "AppName",
    SUBJECT_TYPE_ATTR: "subjectType",
    USER_ID_RES_ATTR : "UserIDResourceAttribute",
    CLIENT_ID_TOK_CLAIM : "ClientIDTokenClaim",
    USER_ID_TOK_CLAIM : "UserIDTokenClaim",
    CLIENT_TENANT_TOK_CLAIM : "ClientTenantTokenClaim",
    USER_TENANT_TOKEN_CLAIM : "TenantTokenClaim",
    ONLY_USER_TOK_CLAIM_ENABLED : "OnlyUserTokenClaimsEnabled",
    GROUP_TOKEN_CLAIM : "GroupsTokenClaim",
    APP_ROLE_TOKEN_CLAIM : "AppRolesTokenClaim",
    TOKEN_VALIDATION_LEVEL : "TokenValidationLevel",
    FULLY_QUALIFIED_SCOPES : "FullyQualifiedScopes",

    USER_CACHE_TTL : "UserCacheTTL",
    USER_CACHE_TTL_DEFAULT : 86400,
    USER_CACHE_MAX_SIZE : "UserCacheMaxSize",
    USER_CACHE_MAX_SIZE_DEFAULT : 10000,

    CACHE_TTL_DEFAULT : 86400,
    CACHE_MAX_SIZE_DEFAULT : 10000,

    META_DATA_CACHE_TTL_DEFAULT : 86400,
    FQS_RESOURCE_CACHE_TTL : "FQSResourceTTL",
    FQS_RESOURCE_CACHE_TTL_DEFAULT : 600,
    DISCOVERY_PATH: '/.well-known/idcs-configuration',
    META_OPENID_CONFIGURATION : 'openid-configuration',
    META_ACCESS_CONFIGURATION : "access-configuration",
    META_ACCESS_CONFIGURATION_ASSERTER_ENDPOINT : "asserter_endpoint",
    META_OPENID_CONFIGURATION_ISSUER : 'issuer',
    META_OPENID_CONFIGURATION_TOKEN_ENDPOINT : 'token_endpoint',
    META_OPENID_CONFIGURATION_AUTHORIZATION_ENDPOINT : 'authorization_endpoint',
    META_OPENID_CONFIGURATOIN_ENDSESSION_ENDPOINT : 'end_session_endpoint',
    META_JWKS_URI : "jwks_uri",

    PARAM_REDIRECT_URI : "redirect_uri",
    PARAM_GRANT_TYPE : "grant_type",
    PARAM_CODE : "code",
    PARAM_NONCE : "nonce",
    PARAM_STATE : "state",
    PARAM_POST_LOGOUT_URI : "post_logout_redirect_uri",
    PARAM_IDTOKEN_HINT : "id_token_hint",
    PARAM_SCOPE : "scope",
    PARAM_CLIENT_ID : "client_id",
    PARAM_RESPONSE_TYPE : "response_type",
    PARAM_ATTRIBUTES : "attributes",
    PARAM_USERNAME : "username",
    PARAM_PASSWORD : "password",
    PARAM_REFRESH_TOKEN : "refresh_token",
    PARAM_ASSERTION : 'assertion',
    PARAM_CLIENT_ASSERTION : 'client_assertion',
    PARAM_CLIENT_ASSERTION_TYPE : 'client_assertion_type',

    GRANT_CLIENT_CRED : "client_credentials",
    GRANT_AUTHZ_CODE : 'authorization_code',
    GRANT_PASSWORD : 'password',
    GRANT_REFRESH_TOKEN : 'refresh_token',
    GRANT_ASSERTION : 'urn:ietf:params:oauth:grant-type:jwt-bearer',

    RESPONSE_TYPE_CODE : "code",
    ASSERTION_TYPE_JWT : 'urn:ietf:params:oauth:client-assertion-type:jwt-bearer',

    ID_TOKEN : "id_token",
    ACCESS_TOKEN : "access_token",
    REFRESH_TOKEN : "refresh_token",

    GET_ME_URL : "/admin/v1/Me",
    GET_USER_URL : "/admin/v1/Users/%s",
    GET_APP_INFO_PATH : "/admin/v1/Apps",
    FQS_FILTER : "?filter=scopes.fqs+eq+%s",
    USER_ATTRUBUTES : "username,displayname,emails,groups,urn:ietf:params:scim:schemas:oracle:idcs:extension:user:User:appRoles",
    IDCS_ASSERTER_SCHEMA : "urn:ietf:params:scim:schemas:oracle:idcs:Asserter",
    IDCS_APPNAME_FILTER_ATTRIB : "appName",
    IDCS_MAPPING_ATTRIBUTE : "mappingAttribute",
    IDCS_MAPPING_ATTRIBUTE_VALUE : "mappingAttributeValue",
    MAPPING_ATTR_ID : "id",
    IDCS_SCHEMAS : "schemas",
    IDCS_INCLUDE_MEMBERSHIPS : "includeMemberships",

    AUTH_BASIC : "Basic %s",
    AUTH_BEARER : "Bearer %s",

    HEADER_AUTHORIZATION : "Authorization",
    HEADER_CONTENT_TYPE : "Content-Type",
    WWW_FORM_ENCODED : "application/x-www-form-urlencoded;charset=UTF-8",
    APPLICATION_JSON : "application/json",

    MY_SCOPES : "urn:opc:idm:__myscopes__",

    CLAIM_USER_NAME : 'userName',
    CLAIM_USER_DISPLAY_NAME : 'displayName',
    CLAIM_USER_ID : 'id',
    CLAIM_USER_IDENTITY_DOMAIN :  'identityDomain',
    CLAIM_USER_GROUPS : 'groups',
    CLAIM_USER_EXTENSIONS : 'urn:ietf:params:scim:schemas:oracle:idcs:extension:user:User',

    CLAIM_GROUP_DISPLAY_NAME : 'display',
    CLAIM_GROUP_ID : 'value',
    CLAIM_GROUP_LOCATION : '$ref',

    CLAIM_APP_ROLES : 'appRoles',
    CLAIM_APP_ROLE_DISPLAY : 'display',
    CLAIM_APP_ROLE_APPNAME : 'appName',
    CLAIM_APP_ROLE_ADMIN : 'adminRole',
    CLAIM_APP_ROLE_APPID : 'appId',
    CLAIM_APP_ROLE_VALUE : 'value',
    CLAIM_APP_ROLE_LOCATION : '$ref',

    HEADER_CLAIM_KEY_ID : "kid",
    HEADER_CLAIM_X5_THUMB : "x5t",
    TOKEN_CLAIM_JTI : "jti",
    TOKEN_CLAIM_EXPIRY : "exp",
    TOKEN_CLAIM_AUDIENCE : "aud",
    TOKEN_CLAIM_ISSUE_AT : "iat",
    TOKEN_CLAIM_ISSUER : "iss",
    TOKEN_CLAIM_SCOPE : "scope",
    TOKEN_CLAIM_TENANT : "tenant",
    TOKEN_CLAIM_USER_APPROLES : "userAppRoles",
    TOKEN_CLAIM_CLIENT_APPROLES : "clientAppRoles",
    TOKEN_CLAIM_SUBJECT : "sub",
    TOKEN_CLAIM_TOKEN_TYPE : "tok_type",
    TOKEN_CLAIM_CLIENT_ID : "client_id",
    TOKEN_CLAIM_USER_ID : "user_id",
    TOKEN_CLAIM_CLIENT_TENANT : "client_tenantname",
    TOKEN_CLAIM_USER_TENANT : "user_tenantname",
    TOKEN_CLAIM_GROUPS : "groups",
    TOKEN_CLAIM_APP_ROLES : "appRoles",
    TOKEN_CLAIM_CLIENT_TENANT_NAME : "client_tenantname",
    TOKEN_CLAIM_SUB_TYPE : "sub_type",
    VALIDATION_LEVEL_NONE : "NONE",
    VALIDATION_LEVEL_SIGNATURE : "SIGNATURE",
    VALIDATION_LEVEL_NORMAL : "NORMAL",
    VALIDATION_LEVEL_FULL : "FULL",
    NECESSARY_AUDIENCE_PREFIX : "urn:opc:resource:scope:",
    LOGICALGUID_AUDIENCE_PREFIX : "urn:opc:lbaas:logicalguid",
    AUDIENCE_SCOPE_ACCOUNT : "urn:opc:resource:scope:account",
    AUDIENCE_SCOPE_TAG : "urn:opc:resource:scope:tag",
    OPEN_ID : "openid"
};

module.exports = IDCSConstants;