export const message670 = {
   "cuks": [
       {
           "id": "1",
           "name": "670",
           "description": "ALZAMIENTO HIPOTECARIO",
            "creationDate": "22/04/2024",
            "cukCode": "AH000100000000000001",
            "foreclosureDate": "22/04/2024",
            "channel": "Personas",
            "status": "11 - Pago de la Operación",
            "clientDni": "12345678-9",
            "clientName": "Juan Pérez",
            "institutionDestination": "012 - Banco Estado",

           "messages": [
            {
                "id": "10123",
                "TSN": "10123",
                "OSN": "10123",
                "NSE": "10123",
                "NSR": "10123",
                "NSQ": "10123",
                "messageCode": "670",
                "destination": "",
                "description": "ALZAMIENTO HIPOTECARIO",
                "priority": "",
                "status": "01",
                "sender": "Corp Banca",
                "creationDate": "23/04/2024",
                "creationTime": "11:00",
                "receiver": "Santander",
                "receivedDate": "24/04/2024",
                "receivedTime": "11:00",
                "documents": "",
                "actions": [],
              },
            {
                "id": "10124",
                "TSN": "10124",
                "OSN": "10124",
                "NSE": "10124",
                "NSR": "10124",
                "NSQ": "10124",
                "messageCode": "671",
                "destination": "",
                "description": "ALZAMIENTO HIPOTECARIO",
                "priority": "",
                "status": "01",
                "sender": "Corp Banca",
                "creationDate": "23/04/2024",
                "creationTime": "11:00",
                "receiver": "Santander",
                "receivedDate": "24/04/2024",
                "receivedTime": "11:00",
                "documents": "",
                "actions": [],
              },
            {
                "id": "10125",
                "TSN": "10125",
                "OSN": "10125",
                "NSE": "10125",
                "NSR": "10125",
                "NSQ": "10125",
                "messageCode": "672",
                "destination": "",
                "description": "ALZAMIENTO HIPOTECARIO",
                "priority": "",
                "status": "01",
                "sender": "Corp Banca",
                "creationDate": "23/04/2024",
                "creationTime": "11:00",
                "receiver": "Santander",
                "receivedDate": "24/04/2024",
                "receivedTime": "11:00",
                "documents": "",
                "actions": [],
              },
            {
                "id": "10126",
                "TSN": "10126",
                "OSN": "10126",
                "NSE": "10126",
                "NSR": "10126",
                "NSQ": "10126",
                "messageCode": "673",
                "destination": "",
                "description": "ALZAMIENTO HIPOTECARIO",
                "priority": "",
                "status": "01",
                "sender": "Corp Banca",
                "creationDate": "23/04/2024",
                "creationTime": "11:00",
                "receiver": "Santander",
                "receivedDate": "24/04/2024",
                "receivedTime": "11:00",
                "documents": "",
                "actions": [],
              },
           ]
       },
       {
           "id": "1",
           "name": "670",
           "description": "ALZAMIENTO HIPOTECARIO",
            "creationDate": "22/04/2024",
            "cukCode": "AH000100000000000001",
            "foreclosureDate": "22/04/2024",
            "channel": "Personas",
            "status": "11 - Pago de la Operación",
            "clientDni": "12345678-9",
            "clientName": "Juan Pérez",
            "institutionDestination": "012 - Banco Estado",

           "messages": [
            {
                "id": "10123",
                "TSN": "10123",
                "OSN": "10123",
                "NSE": "10123",
                "NSR": "10123",
                "NSQ": "10123",
                "messageCode": "670",
                "destination": "",
                "description": "ALZAMIENTO HIPOTECARIO",
                "priority": "",
                "status": "01",
                "sender": "Corp Banca",
                "creationDate": "23/04/2024",
                "creationTime": "11:00",
                "receiver": "Santander",
                "receivedDate": "24/04/2024",
                "receivedTime": "11:00",
                "documents": "",
                "actions": [],
              },
            {
                "id": "10124",
                "TSN": "10124",
                "OSN": "10124",
                "NSE": "10124",
                "NSR": "10124",
                "NSQ": "10124",
                "messageCode": "671",
                "destination": "",
                "description": "ALZAMIENTO HIPOTECARIO",
                "priority": "",
                "status": "01",
                "sender": "Corp Banca",
                "creationDate": "23/04/2024",
                "creationTime": "11:00",
                "receiver": "Santander",
                "receivedDate": "24/04/2024",
                "receivedTime": "11:00",
                "documents": "",
                "actions": [],
              },
            {
                "id": "10125",
                "TSN": "10125",
                "OSN": "10125",
                "NSE": "10125",
                "NSR": "10125",
                "NSQ": "10125",
                "messageCode": "672",
                "destination": "",
                "description": "ALZAMIENTO HIPOTECARIO",
                "priority": "",
                "status": "01",
                "sender": "Corp Banca",
                "creationDate": "23/04/2024",
                "creationTime": "11:00",
                "receiver": "Santander",
                "receivedDate": "24/04/2024",
                "receivedTime": "11:00",
                "documents": "",
                "actions": [],
              },
            {
                "id": "10126",
                "TSN": "10126",
                "OSN": "10126",
                "NSE": "10126",
                "NSR": "10126",
                "NSQ": "10126",
                "messageCode": "673",
                "destination": "",
                "description": "ALZAMIENTO HIPOTECARIO",
                "priority": "",
                "status": "01",
                "sender": "Corp Banca",
                "creationDate": "23/04/2024",
                "creationTime": "11:00",
                "receiver": "Santander",
                "receivedDate": "24/04/2024",
                "receivedTime": "11:00",
                "documents": "",
                "actions": [],
              },
           ]
       },
       {
           "id": "1",
           "name": "670",
           "description": "ALZAMIENTO HIPOTECARIO",
            "creationDate": "22/04/2024",
            "cukCode": "AH000100000000000001",
            "foreclosureDate": "22/04/2024",
            "channel": "Personas",
            "status": "11 - Pago de la Operación",
            "clientDni": "12345678-9",
            "clientName": "Juan Pérez",
            "institutionDestination": "012 - Banco Estado",

           "messages": [
            {
                "id": "10123",
                "TSN": "10123",
                "OSN": "10123",
                "NSE": "10123",
                "NSR": "10123",
                "NSQ": "10123",
                "messageCode": "670",
                "destination": "",
                "description": "ALZAMIENTO HIPOTECARIO",
                "priority": "",
                "status": "01",
                "sender": "Corp Banca",
                "creationDate": "23/04/2024",
                "creationTime": "11:00",
                "receiver": "Santander",
                "receivedDate": "24/04/2024",
                "receivedTime": "11:00",
                "documents": "",
                "actions": [],
              },
            {
                "id": "10124",
                "TSN": "10124",
                "OSN": "10124",
                "NSE": "10124",
                "NSR": "10124",
                "NSQ": "10124",
                "messageCode": "671",
                "destination": "",
                "description": "ALZAMIENTO HIPOTECARIO",
                "priority": "",
                "status": "01",
                "sender": "Corp Banca",
                "creationDate": "23/04/2024",
                "creationTime": "11:00",
                "receiver": "Santander",
                "receivedDate": "24/04/2024",
                "receivedTime": "11:00",
                "documents": "",
                "actions": [],
              },
            {
                "id": "10125",
                "TSN": "10125",
                "OSN": "10125",
                "NSE": "10125",
                "NSR": "10125",
                "NSQ": "10125",
                "messageCode": "672",
                "destination": "",
                "description": "ALZAMIENTO HIPOTECARIO",
                "priority": "",
                "status": "01",
                "sender": "Corp Banca",
                "creationDate": "23/04/2024",
                "creationTime": "11:00",
                "receiver": "Santander",
                "receivedDate": "24/04/2024",
                "receivedTime": "11:00",
                "documents": "",
                "actions": [],
              },
            {
                "id": "10126",
                "TSN": "10126",
                "OSN": "10126",
                "NSE": "10126",
                "NSR": "10126",
                "NSQ": "10126",
                "messageCode": "673",
                "destination": "",
                "description": "ALZAMIENTO HIPOTECARIO",
                "priority": "",
                "status": "01",
                "sender": "Corp Banca",
                "creationDate": "23/04/2024",
                "creationTime": "11:00",
                "receiver": "Santander",
                "receivedDate": "24/04/2024",
                "receivedTime": "11:00",
                "documents": "",
                "actions": [],
              },
           ]
       },
       {
           "id": "1",
           "name": "670",
           "description": "ALZAMIENTO HIPOTECARIO",
            "creationDate": "22/04/2024",
            "cukCode": "AH000100000000000001",
            "foreclosureDate": "22/04/2024",
            "channel": "Personas",
            "status": "11 - Pago de la Operación",
            "clientDni": "12345678-9",
            "clientName": "Juan Pérez",
            "institutionDestination": "012 - Banco Estado",

           "messages": [
            {
                "id": "10123",
                "TSN": "10123",
                "OSN": "10123",
                "NSE": "10123",
                "NSR": "10123",
                "NSQ": "10123",
                "messageCode": "670",
                "destination": "",
                "description": "ALZAMIENTO HIPOTECARIO",
                "priority": "",
                "status": "01",
                "sender": "Corp Banca",
                "creationDate": "23/04/2024",
                "creationTime": "11:00",
                "receiver": "Santander",
                "receivedDate": "24/04/2024",
                "receivedTime": "11:00",
                "documents": "",
                "actions": [],
              },
            {
                "id": "10124",
                "TSN": "10124",
                "OSN": "10124",
                "NSE": "10124",
                "NSR": "10124",
                "NSQ": "10124",
                "messageCode": "671",
                "destination": "",
                "description": "ALZAMIENTO HIPOTECARIO",
                "priority": "",
                "status": "01",
                "sender": "Corp Banca",
                "creationDate": "23/04/2024",
                "creationTime": "11:00",
                "receiver": "Santander",
                "receivedDate": "24/04/2024",
                "receivedTime": "11:00",
                "documents": "",
                "actions": [],
              },
            {
                "id": "10125",
                "TSN": "10125",
                "OSN": "10125",
                "NSE": "10125",
                "NSR": "10125",
                "NSQ": "10125",
                "messageCode": "672",
                "destination": "",
                "description": "ALZAMIENTO HIPOTECARIO",
                "priority": "",
                "status": "01",
                "sender": "Corp Banca",
                "creationDate": "23/04/2024",
                "creationTime": "11:00",
                "receiver": "Santander",
                "receivedDate": "24/04/2024",
                "receivedTime": "11:00",
                "documents": "",
                "actions": [],
              },
            {
                "id": "10126",
                "TSN": "10126",
                "OSN": "10126",
                "NSE": "10126",
                "NSR": "10126",
                "NSQ": "10126",
                "messageCode": "673",
                "destination": "",
                "description": "ALZAMIENTO HIPOTECARIO",
                "priority": "",
                "status": "01",
                "sender": "Corp Banca",
                "creationDate": "23/04/2024",
                "creationTime": "11:00",
                "receiver": "Santander",
                "receivedDate": "24/04/2024",
                "receivedTime": "11:00",
                "documents": "",
                "actions": [],
              },
           ]
       },
       {
           "id": "1",
           "name": "670",
           "description": "ALZAMIENTO HIPOTECARIO",
            "creationDate": "22/04/2024",
            "cukCode": "AH000100000000000001",
            "foreclosureDate": "22/04/2024",
            "channel": "Personas",
            "status": "11 - Pago de la Operación",
            "clientDni": "12345678-9",
            "clientName": "Juan Pérez",
            "institutionDestination": "012 - Banco Estado",

           "messages": [
            {
                "id": "10123",
                "TSN": "10123",
                "OSN": "10123",
                "NSE": "10123",
                "NSR": "10123",
                "NSQ": "10123",
                "messageCode": "670",
                "destination": "",
                "description": "ALZAMIENTO HIPOTECARIO",
                "priority": "",
                "status": "01",
                "sender": "Corp Banca",
                "creationDate": "23/04/2024",
                "creationTime": "11:00",
                "receiver": "Santander",
                "receivedDate": "24/04/2024",
                "receivedTime": "11:00",
                "documents": "",
                "actions": [],
              },
            {
                "id": "10124",
                "TSN": "10124",
                "OSN": "10124",
                "NSE": "10124",
                "NSR": "10124",
                "NSQ": "10124",
                "messageCode": "671",
                "destination": "",
                "description": "ALZAMIENTO HIPOTECARIO",
                "priority": "",
                "status": "01",
                "sender": "Corp Banca",
                "creationDate": "23/04/2024",
                "creationTime": "11:00",
                "receiver": "Santander",
                "receivedDate": "24/04/2024",
                "receivedTime": "11:00",
                "documents": "",
                "actions": [],
              },
            {
                "id": "10125",
                "TSN": "10125",
                "OSN": "10125",
                "NSE": "10125",
                "NSR": "10125",
                "NSQ": "10125",
                "messageCode": "672",
                "destination": "",
                "description": "ALZAMIENTO HIPOTECARIO",
                "priority": "",
                "status": "01",
                "sender": "Corp Banca",
                "creationDate": "23/04/2024",
                "creationTime": "11:00",
                "receiver": "Santander",
                "receivedDate": "24/04/2024",
                "receivedTime": "11:00",
                "documents": "",
                "actions": [],
              },
            {
                "id": "10126",
                "TSN": "10126",
                "OSN": "10126",
                "NSE": "10126",
                "NSR": "10126",
                "NSQ": "10126",
                "messageCode": "673",
                "destination": "",
                "description": "ALZAMIENTO HIPOTECARIO",
                "priority": "",
                "status": "01",
                "sender": "Corp Banca",
                "creationDate": "23/04/2024",
                "creationTime": "11:00",
                "receiver": "Santander",
                "receivedDate": "24/04/2024",
                "receivedTime": "11:00",
                "documents": "",
                "actions": [],
              },
           ]
       },
   ]
}