export enum envVariables {
    NODE_ENV = 'NODE_ENV',
    LOG_FILENAME = 'LOG_FILENAME',
    DATABASE_URL = 'DATABASE_URL',
    ADMIN_CLIENT_URL = 'ADMIN_CLIENT_URL',
    RULE_CLIENT_URL = 'RULE_CLIENT_URL',
    INSTITUTIONS_PATH = 'INSTITUTIONS_PATH',
    SCHEMA_PATH = 'SCHEMA_PATH',
    SCHEMA_TYPES_PATH = 'SCHEMA_TYPES_PATH',
    VALIDATE_MESSAGE = 'VALIDATE_MESSAGE',
}