export const optionsDestination = [
  { label: "Todos", value: "all" },
  {
    name: "HipotecariaSecurityPrincipal",
    Type: "institution",
    description: "Nombre del banco HIPOTECARIA SECURITY PRINCIPAL S.A",
    value: "HipotecariaSecurityPrincipal",
    label: "HIPOTECARIA SECURITY PRINCIPAL S.A",
  },
  {
    name: "SociedadEmisoraDeTarjetasLosHeroes",
    Type: "institution",
    description:
      "Nombre del banco SOCIEDAD EMISORA DE TARJETAS LOS HEROES S.A.",
    value: "SociedadEmisoraDeTarjetasLosHeroes",
    label: "SOCIEDAD EMISORA DE TARJETAS LOS HEROES S.A.",
  },
  {
    name: "InkasTransporteDeValores",
    Type: "institution",
    description: "Nombre del banco INKAS TRANSPORTE DE VALORES SPA",
    value: "InkasTransporteDeValores",
    label: "INKAS TRANSPORTE DE VALORES SPA",
  },
  {
    name: "LosAndesTarjetasDePrepago",
    Type: "institution",
    description: "Nombre del banco LOS ANDES TARJETAS DE PREPAGO S.A.",
    value: "LosAndesTarjetasDePrepago",
    label: "LOS ANDES TARJETAS DE PREPAGO S.A.",
  },
  {
    name: "TenpoPrepago",
    Type: "institution",
    description: "Nombre del banco TENPO PREPAGO S.A.",
    value: "TenpoPrepago",
    label: "TENPO PREPAGO S.A.",
  },
  {
    name: "DepositoCentralDeValores",
    Type: "institution",
    description: "Nombre del banco DEPOSITO CENTRAL DE VALORES",
    value: "DepositoCentralDeValores",
    label: "DEPOSITO CENTRAL DE VALORES",
  },
  {
    name: "BrinksChile",
    Type: "institution",
    description: "Nombre del banco BRINK'S CHILE S.A.",
    value: "BrinksChile",
    label: "BRINK'S CHILE S.A.",
  },
  {
    name: "Bci",
    Type: "institution",
    description: "Nombre del banco BANCO DE CREDITO E INVERSIONES",
    value: "Bci",
    label: "BANCO DE CREDITO E INVERSIONES",
  },
  {
    name: "BancoSantander",
    Type: "institution",
    description: "Nombre del banco BANCO SANTANDER-CHILE",
    value: "BancoSantander",
    label: "BANCO SANTANDER-CHILE",
  },
  {
    name: "HsbcBank",
    Type: "institution",
    description: "Nombre del banco HSBC BANK (CHILE)",
    value: "HsbcBank",
    label: "HSBC BANK (CHILE)",
  },
  {
    name: "ItauCorpbanca",
    Type: "institution",
    description: "Nombre del banco ITAÚ CORPBANCA",
    value: "ItauCorpbanca",
    label: "ITAÚ CORPBANCA",
  },
  {
    name: "CorpBanca",
    Type: "institution",
    description: "Nombre del banco CORP BANCA",
    value: "CorpBanca",
    label: "CORP BANCA",
  },
  {
    name: "JpmorganChaseBank",
    Type: "institution",
    description: "Nombre del banco JPMORGAN CHASE BANK, N.A.",
    value: "JpmorganChaseBank",
    label: "JPMORGAN CHASE BANK, N.A.",
  },
  {
    name: "BancoSecurity",
    Type: "institution",
    description: "Nombre del banco BANCO SECURITY",
    value: "BancoSecurity",
    label: "BANCO SECURITY",
  },
  {
    name: "BancoFalabella",
    Type: "institution",
    description: "Nombre del banco BANCO FALABELLA",
    value: "BancoFalabella",
    label: "BANCO FALABELLA",
  },
  {
    name: "arica",
    Type: "region",
    description: "Región de Arica y Parinacota",
    value: "arica",
    label: "Región de Arica y Parinacota",
  },
  {
    name: "tarapaca",
    Type: "region",
    description: "Región de Tarapacá",
    value: "tarapaca",
    label: "Región de Tarapacá",
  },
  {
    name: "antofagasta",
    Type: "region",
    description: "Región de Antofagasta",
    value: "antofagasta",
    label: "Región de Antofagasta",
  },
  {
    name: "atacama",
    Type: "region",
    description: "Región de Atacama",
    value: "atacama",
    label: "Región de Atacama",
  },
  {
    name: "coquimbo",
    Type: "region",
    description: "Región de Coquimbo",
    value: "coquimbo",
    label: "Región de Coquimbo",
  },
  {
    name: "valparaiso",
    Type: "region",
    description: "Región de Valparaíso",
    value: "valparaiso",
    label: "Región de Valparaíso",
  },
  {
    name: "metropolitana",
    Type: "region",
    description: "Región Metropolitana",
    value: "metropolitana",
    label: "Región Metropolitana",
  },
  {
    name: "oHiggins",
    Type: "region",
    description: "Región del Libertador General Bernardo O'Higgins",
    value: "oHiggins",
    label: "Región del Libertador General Bernardo O'Higgins",
  },
  {
    name: "maule",
    Type: "region",
    description: "Región del Maule",
    value: "maule",
    label: "Región del Maule",
  },
  {
    name: "nuble",
    Type: "region",
    description: "Región de Ñuble",
    value: "nuble",
    label: "Región de Ñuble",
  },
  {
    name: "biobio",
    Type: "region",
    description: "Región del Biobío",
    value: "biobio",
    label: "Región del Biobío",
  },
  {
    name: "araucania",
    Type: "region",
    description: "Región de La Araucanía",
    value: "araucania",
    label: "Región de La Araucanía",
  },
  {
    name: "losRios",
    Type: "region",
    description: "Región de Los Ríos",
    value: "losRios",
    label: "Región de Los Ríos",
  },
  {
    name: "losLagos",
    Type: "region",
    description: "Región de Los Lagos",
    value: "losLagos",
    label: "Región de Los Lagos",
  },
  {
    name: "aysen",
    Type: "region",
    description: "Región de Aysén del General Carlos Ibáñez del Campo",
    value: "aysen",
    label: "Región de Aysén del General Carlos Ibáñez del Campo",
  },
  {
    name: "magallanes",
    Type: "region",
    description: "Región de Magallanes y de la Antártica Chilena",
    value: "magallanes",
    label: "Región de Magallanes y de la Antártica Chilena",
  },
];

export const optionsRegion = [
  { label: "Todos", value: "all" },
  {
    name: "aisen",
    Type: "Commune",
    description: "Aisén",
    value: "aisen",
    label: "Aisén",
  },
  {
    name: "algarrobo",
    Type: "Commune",
    description: "Algarrobo",
    value: "algarrobo",
    label: "Algarrobo",
  },
  {
    name: "alhue",
    Type: "Commune",
    description: "Alhué",
    value: "alhue",
    label: "Alhué",
  },
  {
    name: "altoBiobio",
    Type: "Commune",
    description: "Alto Biobío",
    value: "altoBiobio",
    label: "Alto Biobío",
  },
  {
    name: "altoDelCarmen",
    Type: "Commune",
    description: "Alto Del Carmen",
    value: "altoDelCarmen",
    label: "Alto Del Carmen",
  },
  {
    name: "altoHospicio",
    Type: "Commune",
    description: "Alto Hospicio",
    value: "altoHospicio",
    label: "Alto Hospicio",
  },
  {
    name: "ancud",
    Type: "Commune",
    description: "Ancud",
    value: "ancud",
    label: "Ancud",
  },
  {
    name: "andacollo",
    Type: "Commune",
    description: "Andacollo",
    value: "andacollo",
    label: "Andacollo",
  },
  {
    name: "angol",
    Type: "Commune",
    description: "Angol",
    value: "angol",
    label: "Angol",
  },
  {
    name: "antofagasta",
    Type: "Commune",
    description: "Antofagasta",
    value: "antofagasta",
    label: "Antofagasta",
  },
  {
    name: "antuco",
    Type: "Commune",
    description: "Antuco",
    value: "antuco",
    label: "Antuco",
  },
  {
    name: "antartica",
    Type: "Commune",
    description: "Antártica",
    value: "antartica",
    label: "Antártica",
  },
  {
    name: "arauco",
    Type: "Commune",
    description: "Arauco",
    value: "arauco",
    label: "Arauco",
  },
  {
    name: "arica",
    Type: "Commune",
    description: "Arica",
    value: "arica",
    label: "Arica",
  },
  {
    name: "buin",
    Type: "Commune",
    description: "Buin",
    value: "buin",
    label: "Buin",
  },
  {
    name: "bulnes",
    Type: "Commune",
    description: "Bulnes",
    value: "bulnes",
    label: "Bulnes",
  },
  {
    name: "cabildo",
    Type: "Commune",
    description: "Cabildo",
    value: "cabildo",
    label: "Cabildo",
  },
  {
    name: "cabodeHornos",
    Type: "Commune",
    description: "Cabo De Hornos",
    value: "cabodeHornos",
    label: "Cabo De Hornos",
  },
  {
    name: "cabrero",
    Type: "Commune",
    description: "Cabrero",
    value: "cabrero",
    label: "Cabrero",
  },
  {
    name: "calama",
    Type: "Commune",
    description: "Calama",
    value: "calama",
    label: "Calama",
  },
  {
    name: "calbuco",
    Type: "Commune",
    description: "Calbuco",
    value: "calbuco",
    label: "Calbuco",
  },
  {
    name: "caldera",
    Type: "Commune",
    description: "Caldera",
    value: "caldera",
    label: "Caldera",
  },
  {
    name: "calera",
    Type: "Commune",
    description: "Calera",
    value: "calera",
    label: "Calera",
  },
  {
    name: "caleradeTango",
    Type: "Commune",
    description: "Calera De Tango",
    value: "caleradeTango",
    label: "Calera De Tango",
  },
  {
    name: "calleLarga",
    Type: "Commune",
    description: "Calle Larga",
    value: "calleLarga",
    label: "Calle Larga",
  },
  {
    name: "camarones",
    Type: "Commune",
    description: "Camarones",
    value: "camarones",
    label: "Camarones",
  },
  {
    name: "camina",
    Type: "Commune",
    description: "Camiña",
    value: "camina",
    label: "Camiña",
  },
  {
    name: "canela",
    Type: "Commune",
    description: "Canela",
    value: "canela",
    label: "Canela",
  },
  {
    name: "carahue",
    Type: "Commune",
    description: "Carahue",
    value: "carahue",
    label: "Carahue",
  },
  {
    name: "cartagena",
    Type: "Commune",
    description: "Cartagena",
    value: "cartagena",
    label: "Cartagena",
  },
  {
    name: "casablanca",
    Type: "Commune",
    description: "Casablanca",
    value: "casablanca",
    label: "Casablanca",
  },
  {
    name: "castro",
    Type: "Commune",
    description: "Castro",
    value: "castro",
    label: "Castro",
  },
  {
    name: "catemu",
    Type: "Commune",
    description: "Catemu",
    value: "catemu",
    label: "Catemu",
  },
  {
    name: "cauquenes",
    Type: "Commune",
    description: "Cauquenes",
    value: "cauquenes",
    label: "Cauquenes",
  },
  {
    name: "canete",
    Type: "Commune",
    description: "Cañete",
    value: "canete",
    label: "Cañete",
  },
  {
    name: "cerrillos",
    Type: "Commune",
    description: "Cerrillos",
    value: "cerrillos",
    label: "Cerrillos",
  },
  {
    name: "cerroNavia",
    Type: "Commune",
    description: "Cerro Navia",
    value: "cerroNavia",
    label: "Cerro Navia",
  },
  {
    name: "chaiten",
    Type: "Commune",
    description: "Chaitén",
    value: "chaiten",
    label: "Chaitén",
  },
  {
    name: "chanco",
    Type: "Commune",
    description: "Chanco",
    value: "chanco",
    label: "Chanco",
  },
  {
    name: "chanaral",
    Type: "Commune",
    description: "Chañaral",
    value: "chanaral",
    label: "Chañaral",
  },
  {
    name: "chiguayante",
    Type: "Commune",
    description: "Chiguayante",
    value: "chiguayante",
    label: "Chiguayante",
  },
  {
    name: "chileChico",
    Type: "Commune",
    description: "Chile Chico",
    value: "chileChico",
    label: "Chile Chico",
  },
  {
    name: "chillan",
    Type: "Commune",
    description: "Chillán",
    value: "chillan",
    label: "Chillán",
  },
  {
    name: "chillanViejo",
    Type: "Commune",
    description: "Chillán Viejo",
    value: "chillanViejo",
    label: "Chillán Viejo",
  },
  {
    name: "chimbarongo",
    Type: "Commune",
    description: "Chimbarongo",
    value: "chimbarongo",
    label: "Chimbarongo",
  },
  {
    name: "cholchol",
    Type: "Commune",
    description: "Cholchol",
    value: "cholchol",
    label: "Cholchol",
  },
  {
    name: "chonchi",
    Type: "Commune",
    description: "Chonchi",
    value: "chonchi",
    label: "Chonchi",
  },
  {
    name: "chepica",
    Type: "Commune",
    description: "Chépica",
    value: "chepica",
    label: "Chépica",
  },
  {
    name: "cisnes",
    Type: "Commune",
    description: "Cisnes",
    value: "cisnes",
    label: "Cisnes",
  },
  {
    name: "cobquecura",
    Type: "Commune",
    description: "Cobquecura",
    value: "cobquecura",
    label: "Cobquecura",
  },
  {
    name: "cochamo",
    Type: "Commune",
    description: "Cochamó",
    value: "cochamo",
    label: "Cochamó",
  },
  {
    name: "cochrane",
    Type: "Commune",
    description: "Cochrane",
    value: "cochrane",
    label: "Cochrane",
  },
  {
    name: "codegua",
    Type: "Commune",
    description: "Codegua",
    value: "codegua",
    label: "Codegua",
  },
  {
    name: "coelemu",
    Type: "Commune",
    description: "Coelemu",
    value: "coelemu",
    label: "Coelemu",
  },
  {
    name: "coihaique",
    Type: "Commune",
    description: "Coihaique",
    value: "coihaique",
    label: "Coihaique",
  },
  {
    name: "coihueco",
    Type: "Commune",
    description: "Coihueco",
    value: "coihueco",
    label: "Coihueco",
  },
  {
    name: "coinco",
    Type: "Commune",
    description: "Coinco",
    value: "coinco",
    label: "Coinco",
  },
  {
    name: "colbun",
    Type: "Commune",
    description: "Colbún",
    value: "colbun",
    label: "Colbún",
  },
  {
    name: "colchane",
    Type: "Commune",
    description: "Colchane",
    value: "colchane",
    label: "Colchane",
  },
  {
    name: "colina",
    Type: "Commune",
    description: "Colina",
    value: "colina",
    label: "Colina",
  },
  {
    name: "collipulli",
    Type: "Commune",
    description: "Collipulli",
    value: "collipulli",
    label: "Collipulli",
  },
  {
    name: "coltauco",
    Type: "Commune",
    description: "Coltauco",
    value: "coltauco",
    label: "Coltauco",
  },
  {
    name: "combarbala",
    Type: "Commune",
    description: "Combarbalá",
    value: "combarbala",
    label: "Combarbalá",
  },
  {
    name: "concepcion",
    Type: "Commune",
    description: "Concepción",
    value: "concepcion",
    label: "Concepción",
  },
  {
    name: "conchali",
    Type: "Commune",
    description: "Conchalí",
    value: "conchali",
    label: "Conchalí",
  },
  {
    name: "concon",
    Type: "Commune",
    description: "Concón",
    value: "concon",
    label: "Concón",
  },
  {
    name: "constitucion",
    Type: "Commune",
    description: "Constitución",
    value: "constitucion",
    label: "Constitución",
  },
  {
    name: "contulmo",
    Type: "Commune",
    description: "Contulmo",
    value: "contulmo",
    label: "Contulmo",
  },
  {
    name: "copiapo",
    Type: "Commune",
    description: "Copiapó",
    value: "copiapo",
    label: "Copiapó",
  },
  {
    name: "coquimbo",
    Type: "Commune",
    description: "Coquimbo",
    value: "coquimbo",
    label: "Coquimbo",
  },
  {
    name: "coronel",
    Type: "Commune",
    description: "Coronel",
    value: "coronel",
    label: "Coronel",
  },
  {
    name: "corral",
    Type: "Commune",
    description: "Corral",
    value: "corral",
    label: "Corral",
  },
  {
    name: "cunco",
    Type: "Commune",
    description: "Cunco",
    value: "cunco",
    label: "Cunco",
  },
  {
    name: "curacautin",
    Type: "Commune",
    description: "Curacautín",
    value: "curacautin",
    label: "Curacautín",
  },
  {
    name: "curacavi",
    Type: "Commune",
    description: "Curacaví",
    value: "curacavi",
    label: "Curacaví",
  },
  {
    name: "curacodeVelez",
    Type: "Commune",
    description: "Curaco De Vélez",
    value: "curacodeVelez",
    label: "Curaco De Vélez",
  },
  {
    name: "curanilahue",
    Type: "Commune",
    description: "Curanilahue",
    value: "curanilahue",
    label: "Curanilahue",
  },
  {
    name: "curarrehue",
    Type: "Commune",
    description: "Curarrehue",
    value: "curarrehue",
    label: "Curarrehue",
  },
  {
    name: "curepto",
    Type: "Commune",
    description: "Curepto",
    value: "curepto",
    label: "Curepto",
  },
  {
    name: "curico",
    Type: "Commune",
    description: "Curicó",
    value: "curico",
    label: "Curicó",
  },
  {
    name: "dalcahue",
    Type: "Commune",
    description: "Dalcahue",
    value: "dalcahue",
    label: "Dalcahue",
  },
  {
    name: "diegodeAlmagro",
    Type: "Commune",
    description: "Diego De Almagro",
    value: "diegodeAlmagro",
    label: "Diego De Almagro",
  },
  {
    name: "donihue",
    Type: "Commune",
    description: "Doñihue",
    value: "donihue",
    label: "Doñihue",
  },
  {
    name: "elBosque",
    Type: "Commune",
    description: "El Bosque",
    value: "elBosque",
    label: "El Bosque",
  },
  {
    name: "elCarmen",
    Type: "Commune",
    description: "El Carmen",
    value: "elCarmen",
    label: "El Carmen",
  },
  {
    name: "elMonte",
    Type: "Commune",
    description: "El Monte",
    value: "elMonte",
    label: "El Monte",
  },
  {
    name: "elQuisco",
    Type: "Commune",
    description: "El Quisco",
    value: "elQuisco",
    label: "El Quisco",
  },
  {
    name: "elTabo",
    Type: "Commune",
    description: "El Tabo",
    value: "elTabo",
    label: "El Tabo",
  },
  {
    name: "empedrado",
    Type: "Commune",
    description: "Empedrado",
    value: "empedrado",
    label: "Empedrado",
  },
  {
    name: "ercilla",
    Type: "Commune",
    description: "Ercilla",
    value: "ercilla",
    label: "Ercilla",
  },
  {
    name: "estacionCentral",
    Type: "Commune",
    description: "Estación Central",
    value: "estacionCentral",
    label: "Estación Central",
  },
  {
    name: "florida",
    Type: "Commune",
    description: "Florida",
    value: "florida",
    label: "Florida",
  },
  {
    name: "freire",
    Type: "Commune",
    description: "Freire",
    value: "freire",
    label: "Freire",
  },
  {
    name: "freirina",
    Type: "Commune",
    description: "Freirina",
    value: "freirina",
    label: "Freirina",
  },
  {
    name: "fresia",
    Type: "Commune",
    description: "Fresia",
    value: "fresia",
    label: "Fresia",
  },
  {
    name: "frutillar",
    Type: "Commune",
    description: "Frutillar",
    value: "frutillar",
    label: "Frutillar",
  },
  {
    name: "futaleufu",
    Type: "Commune",
    description: "Futaleufú",
    value: "futaleufu",
    label: "Futaleufú",
  },
  {
    name: "futrono",
    Type: "Commune",
    description: "Futrono",
    value: "futrono",
    label: "Futrono",
  },
  {
    name: "galvarino",
    Type: "Commune",
    description: "Galvarino",
    value: "galvarino",
    label: "Galvarino",
  },
  {
    name: "generalLagos",
    Type: "Commune",
    description: "General Lagos",
    value: "generalLagos",
    label: "General Lagos",
  },
  {
    name: "gorbea",
    Type: "Commune",
    description: "Gorbea",
    value: "gorbea",
    label: "Gorbea",
  },
  {
    name: "graneros",
    Type: "Commune",
    description: "Graneros",
    value: "graneros",
    label: "Graneros",
  },
  {
    name: "guaitecas",
    Type: "Commune",
    description: "Guaitecas",
    value: "guaitecas",
    label: "Guaitecas",
  },
  {
    name: "hijuelas",
    Type: "Commune",
    description: "Hijuelas",
    value: "hijuelas",
    label: "Hijuelas",
  },
  {
    name: "hualaihue",
    Type: "Commune",
    description: "Hualaihué",
    value: "hualaihue",
    label: "Hualaihué",
  },
  {
    name: "hualane",
    Type: "Commune",
    description: "Hualañé",
    value: "hualane",
    label: "Hualañé",
  },
  {
    name: "hualpen",
    Type: "Commune",
    description: "Hualpén",
    value: "hualpen",
    label: "Hualpén",
  },
  {
    name: "hualqui",
    Type: "Commune",
    description: "Hualqui",
    value: "hualqui",
    label: "Hualqui",
  },
  {
    name: "huara",
    Type: "Commune",
    description: "Huara",
    value: "huara",
    label: "Huara",
  },
  {
    name: "huasco",
    Type: "Commune",
    description: "Huasco",
    value: "huasco",
    label: "Huasco",
  },
  {
    name: "huechuraba",
    Type: "Commune",
    description: "Huechuraba",
    value: "huechuraba",
    label: "Huechuraba",
  },
  {
    name: "illapel",
    Type: "Commune",
    description: "Illapel",
    value: "illapel",
    label: "Illapel",
  },
  {
    name: "independencia",
    Type: "Commune",
    description: "Independencia",
    value: "independencia",
    label: "Independencia",
  },
  {
    name: "iquique",
    Type: "Commune",
    description: "Iquique",
    value: "iquique",
    label: "Iquique",
  },
  {
    name: "islaDeMaipo",
    Type: "Commune",
    description: "Isla De Maipo",
    value: "islaDeMaipo",
    label: "Isla De Maipo",
  },
  {
    name: "islaDePascua",
    Type: "Commune",
    description: "Isla De Pascua",
    value: "islaDePascua",
    label: "Isla De Pascua",
  },
  {
    name: "juanFernandez",
    Type: "Commune",
    description: "Juan Fernández",
    value: "juanFernandez",
    label: "Juan Fernández",
  },
  {
    name: "laCisterna",
    Type: "Commune",
    description: "La Cisterna",
    value: "laCisterna",
    label: "La Cisterna",
  },
  {
    name: "laCruz",
    Type: "Commune",
    description: "La Cruz",
    value: "laCruz",
    label: "La Cruz",
  },
  {
    name: "laEstrella",
    Type: "Commune",
    description: "La Estrella",
    value: "laEstrella",
    label: "La Estrella",
  },
  {
    name: "laFlorida",
    Type: "Commune",
    description: "La Florida",
    value: "laFlorida",
    label: "La Florida",
  },
  {
    name: "laGranja",
    Type: "Commune",
    description: "La Granja",
    value: "laGranja",
    label: "La Granja",
  },
  {
    name: "laHiguera",
    Type: "Commune",
    description: "La Higuera",
    value: "laHiguera",
    label: "La Higuera",
  },
  {
    name: "laLigua",
    Type: "Commune",
    description: "La Ligua",
    value: "laLigua",
    label: "La Ligua",
  },
  {
    name: "laPintana",
    Type: "Commune",
    description: "La Pintana",
    value: "laPintana",
    label: "La Pintana",
  },
  {
    name: "laReina",
    Type: "Commune",
    description: "La Reina",
    value: "laReina",
    label: "La Reina",
  },
  {
    name: "laSerena",
    Type: "Commune",
    description: "La Serena",
    value: "laSerena",
    label: "La Serena",
  },
  {
    name: "laUnion",
    Type: "Commune",
    description: "La Unión",
    value: "laUnion",
    label: "La Unión",
  },
  {
    name: "lagoRanco",
    Type: "Commune",
    description: "Lago Ranco",
    value: "lagoRanco",
    label: "Lago Ranco",
  },
  {
    name: "lagoVerde",
    Type: "Commune",
    description: "Lago Verde",
    value: "lagoVerde",
    label: "Lago Verde",
  },
  {
    name: "lagunaBlanca",
    Type: "Commune",
    description: "Laguna Blanca",
    value: "lagunaBlanca",
    label: "Laguna Blanca",
  },
  {
    name: "laja",
    Type: "Commune",
    description: "Laja",
    value: "laja",
    label: "Laja",
  },
  {
    name: "lampa",
    Type: "Commune",
    description: "Lampa",
    value: "lampa",
    label: "Lampa",
  },
  {
    name: "lanco",
    Type: "Commune",
    description: "Lanco",
    value: "lanco",
    label: "Lanco",
  },
  {
    name: "lasCabras",
    Type: "Commune",
    description: "Las Cabras",
    value: "lasCabras",
    label: "Las Cabras",
  },
  {
    name: "lasCondes",
    Type: "Commune",
    description: "Las Condes",
    value: "lasCondes",
    label: "Las Condes",
  },
  {
    name: "lautaro",
    Type: "Commune",
    description: "Lautaro",
    value: "lautaro",
    label: "Lautaro",
  },
  {
    name: "lebu",
    Type: "Commune",
    description: "Lebu",
    value: "lebu",
    label: "Lebu",
  },
  {
    name: "licanten",
    Type: "Commune",
    description: "Licantén",
    value: "licanten",
    label: "Licantén",
  },
  {
    name: "limache",
    Type: "Commune",
    description: "Limache",
    value: "limache",
    label: "Limache",
  },
  {
    name: "linares",
    Type: "Commune",
    description: "Linares",
    value: "linares",
    label: "Linares",
  },
  {
    name: "litueche",
    Type: "Commune",
    description: "Litueche",
    value: "litueche",
    label: "Litueche",
  },
  {
    name: "llaillay",
    Type: "Commune",
    description: "Llaillay",
    value: "llaillay",
    label: "Llaillay",
  },
  {
    name: "llanquihue",
    Type: "Commune",
    description: "Llanquihue",
    value: "llanquihue",
    label: "Llanquihue",
  },
  {
    name: "loBarnechea",
    Type: "Commune",
    description: "Lo Barnechea",
    value: "loBarnechea",
    label: "Lo Barnechea",
  },
  {
    name: "loEspejo",
    Type: "Commune",
    description: "Lo Espejo",
    value: "loEspejo",
    label: "Lo Espejo",
  },
  {
    name: "loPrado",
    Type: "Commune",
    description: "Lo Prado",
    value: "loPrado",
    label: "Lo Prado",
  },
  {
    name: "lolol",
    Type: "Commune",
    description: "Lolol",
    value: "lolol",
    label: "Lolol",
  },
  {
    name: "loncoche",
    Type: "Commune",
    description: "Loncoche",
    value: "loncoche",
    label: "Loncoche",
  },
  {
    name: "longavi",
    Type: "Commune",
    description: "Longaví",
    value: "longavi",
    label: "Longaví",
  },
  {
    name: "lonquimay",
    Type: "Commune",
    description: "Lonquimay",
    value: "lonquimay",
    label: "Lonquimay",
  },
  {
    name: "losAndes",
    Type: "Commune",
    description: "Los Andes",
    value: "losAndes",
    label: "Los Andes",
  },
  {
    name: "losLagos",
    Type: "Commune",
    description: "Los Lagos",
    value: "losLagos",
    label: "Los Lagos",
  },
  {
    name: "losMuermos",
    Type: "Commune",
    description: "Los Muermos",
    value: "losMuermos",
    label: "Los Muermos",
  },
  {
    name: "losSauces",
    Type: "Commune",
    description: "Los Sauces",
    value: "losSauces",
    label: "Los Sauces",
  },
  {
    name: "losVilos",
    Type: "Commune",
    description: "Los Vilos",
    value: "losVilos",
    label: "Los Vilos",
  },
  {
    name: "losAlamos",
    Type: "Commune",
    description: "Los Álamos",
    value: "losAlamos",
    label: "Los Álamos",
  },
  {
    name: "losAngeles",
    Type: "Commune",
    description: "Los Ángeles",
    value: "losAngeles",
    label: "Los Ángeles",
  },
  {
    name: "lota",
    Type: "Commune",
    description: "Lota",
    value: "lota",
    label: "Lota",
  },
  {
    name: "lumaco",
    Type: "Commune",
    description: "Lumaco",
    value: "lumaco",
    label: "Lumaco",
  },
  {
    name: "machali",
    Type: "Commune",
    description: "Machalí",
    value: "machali",
    label: "Machalí",
  },
  {
    name: "macul",
    Type: "Commune",
    description: "Macul",
    value: "macul",
    label: "Macul",
  },
  {
    name: "maipu",
    Type: "Commune",
    description: "Maipú",
    value: "maipu",
    label: "Maipú",
  },
  {
    name: "malloa",
    Type: "Commune",
    description: "Malloa",
    value: "malloa",
    label: "Malloa",
  },
  {
    name: "marchihue",
    Type: "Commune",
    description: "Marchihue",
    value: "marchihue",
    label: "Marchihue",
  },
  {
    name: "mariquina",
    Type: "Commune",
    description: "Mariquina",
    value: "mariquina",
    label: "Mariquina",
  },
  {
    name: "mariaElena",
    Type: "Commune",
    description: "María Elena",
    value: "mariaElena",
    label: "María Elena",
  },
  {
    name: "mariaPinto",
    Type: "Commune",
    description: "María Pinto",
    value: "mariaPinto",
    label: "María Pinto",
  },
  {
    name: "maule",
    Type: "Commune",
    description: "Maule",
    value: "maule",
    label: "Maule",
  },
  {
    name: "maullin",
    Type: "Commune",
    description: "Maullín",
    value: "maullin",
    label: "Maullín",
  },
  {
    name: "mejillones",
    Type: "Commune",
    description: "Mejillones",
    value: "mejillones",
    label: "Mejillones",
  },
  {
    name: "melipeuco",
    Type: "Commune",
    description: "Melipeuco",
    value: "melipeuco",
    label: "Melipeuco",
  },
  {
    name: "melipilla",
    Type: "Commune",
    description: "Melipilla",
    value: "melipilla",
    label: "Melipilla",
  },
  {
    name: "molina",
    Type: "Commune",
    description: "Molina",
    value: "molina",
    label: "Molina",
  },
  {
    name: "montePatria",
    Type: "Commune",
    description: "Monte Patria",
    value: "montePatria",
    label: "Monte Patria",
  },
  {
    name: "mostazal",
    Type: "Commune",
    description: "Mostazal",
    value: "mostazal",
    label: "Mostazal",
  },
  {
    name: "mulchen",
    Type: "Commune",
    description: "Mulchén",
    value: "mulchen",
    label: "Mulchén",
  },
  {
    name: "mafil",
    Type: "Commune",
    description: "Máfil",
    value: "mafil",
    label: "Máfil",
  },
  {
    name: "nacimiento",
    Type: "Commune",
    description: "Nacimiento",
    value: "nacimiento",
    label: "Nacimiento",
  },
  {
    name: "nancagua",
    Type: "Commune",
    description: "Nancagua",
    value: "nancagua",
    label: "Nancagua",
  },
  {
    name: "natales",
    Type: "Commune",
    description: "Natales",
    value: "natales",
    label: "Natales",
  },
  {
    name: "navidad",
    Type: "Commune",
    description: "Navidad",
    value: "navidad",
    label: "Navidad",
  },
  {
    name: "negrete",
    Type: "Commune",
    description: "Negrete",
    value: "negrete",
    label: "Negrete",
  },
  {
    name: "ninhue",
    Type: "Commune",
    description: "Ninhue",
    value: "ninhue",
    label: "Ninhue",
  },
  {
    name: "nogales",
    Type: "Commune",
    description: "Nogales",
    value: "nogales",
    label: "Nogales",
  },
  {
    name: "nuevaImperial",
    Type: "Commune",
    description: "Nueva Imperial",
    value: "nuevaImperial",
    label: "Nueva Imperial",
  },
  {
    name: "olivar",
    Type: "Commune",
    description: "Olivar",
    value: "olivar",
    label: "Olivar",
  },
  {
    name: "ollague",
    Type: "Commune",
    description: "Ollagüe",
    value: "ollague",
    label: "Ollagüe",
  },
  {
    name: "olmue",
    Type: "Commune",
    description: "Olmué",
    value: "olmue",
    label: "Olmué",
  },
  {
    name: "osorno",
    Type: "Commune",
    description: "Osorno",
    value: "osorno",
    label: "Osorno",
  },
  {
    name: "ovalle",
    Type: "Commune",
    description: "Ovalle",
    value: "ovalle",
    label: "Ovalle",
  },
  {
    name: "oHiggins",
    Type: "Commune",
    description: "O'Higgins",
    value: "oHiggins",
    label: "O'Higgins",
  },
  {
    name: "padreHurtado",
    Type: "Commune",
    description: "Padre Hurtado",
    value: "padreHurtado",
    label: "Padre Hurtado",
  },
  {
    name: "padreLasCasas",
    Type: "Commune",
    description: "Padre Las Casas",
    value: "padreLasCasas",
    label: "Padre Las Casas",
  },
  {
    name: "paihuano",
    Type: "Commune",
    description: "Paihuano",
    value: "paihuano",
    label: "Paihuano",
  },
  {
    name: "paillaco",
    Type: "Commune",
    description: "Paillaco",
    value: "paillaco",
    label: "Paillaco",
  },
  {
    name: "paine",
    Type: "Commune",
    description: "Paine",
    value: "paine",
    label: "Paine",
  },
  {
    name: "palena",
    Type: "Commune",
    description: "Palena",
    value: "palena",
    label: "Palena",
  },
  {
    name: "palmilla",
    Type: "Commune",
    description: "Palmilla",
    value: "palmilla",
    label: "Palmilla",
  },
  {
    name: "panguipulli",
    Type: "Commune",
    description: "Panguipulli",
    value: "panguipulli",
    label: "Panguipulli",
  },
  {
    name: "panquehue",
    Type: "Commune",
    description: "Panquehue",
    value: "panquehue",
    label: "Panquehue",
  },
  {
    name: "papudo",
    Type: "Commune",
    description: "Papudo",
    value: "papudo",
    label: "Papudo",
  },
  {
    name: "paredones",
    Type: "Commune",
    description: "Paredones",
    value: "paredones",
    label: "Paredones",
  },
  {
    name: "parral",
    Type: "Commune",
    description: "Parral",
    value: "parral",
    label: "Parral",
  },
  {
    name: "pedroAguirreCerda",
    Type: "Commune",
    description: "Pedro Aguirre Cerda",
    value: "pedroAguirreCerda",
    label: "Pedro Aguirre Cerda",
  },
  {
    name: "pelarco",
    Type: "Commune",
    description: "Pelarco",
    value: "pelarco",
    label: "Pelarco",
  },
  {
    name: "pelluhue",
    Type: "Commune",
    description: "Pelluhue",
    value: "pelluhue",
    label: "Pelluhue",
  },
  {
    name: "pemuco",
    Type: "Commune",
    description: "Pemuco",
    value: "pemuco",
    label: "Pemuco",
  },
  {
    name: "pencahue",
    Type: "Commune",
    description: "Pencahue",
    value: "pencahue",
    label: "Pencahue",
  },
  {
    name: "penco",
    Type: "Commune",
    description: "Penco",
    value: "penco",
    label: "Penco",
  },
  {
    name: "peralillo",
    Type: "Commune",
    description: "Peralillo",
    value: "peralillo",
    label: "Peralillo",
  },
  {
    name: "perquenco",
    Type: "Commune",
    description: "Perquenco",
    value: "perquenco",
    label: "Perquenco",
  },
  {
    name: "petorca",
    Type: "Commune",
    description: "Petorca",
    value: "petorca",
    label: "Petorca",
  },
  {
    name: "peumo",
    Type: "Commune",
    description: "Peumo",
    value: "peumo",
    label: "Peumo",
  },
  {
    name: "penaflor",
    Type: "Commune",
    description: "Peñaflor",
    value: "penaflor",
    label: "Peñaflor",
  },
  {
    name: "penalolen",
    Type: "Commune",
    description: "Peñalolén",
    value: "penalolen",
    label: "Peñalolén",
  },
  {
    name: "pica",
    Type: "Commune",
    description: "Pica",
    value: "pica",
    label: "Pica",
  },
  {
    name: "pichidegua",
    Type: "Commune",
    description: "Pichidegua",
    value: "pichidegua",
    label: "Pichidegua",
  },
  {
    name: "pichilemu",
    Type: "Commune",
    description: "Pichilemu",
    value: "pichilemu",
    label: "Pichilemu",
  },
  {
    name: "pinto",
    Type: "Commune",
    description: "Pinto",
    value: "pinto",
    label: "Pinto",
  },
  {
    name: "pirque",
    Type: "Commune",
    description: "Pirque",
    value: "pirque",
    label: "Pirque",
  },
  {
    name: "pitrufquen",
    Type: "Commune",
    description: "Pitrufquén",
    value: "pitrufquen",
    label: "Pitrufquén",
  },
  {
    name: "placilla",
    Type: "Commune",
    description: "Placilla",
    value: "placilla",
    label: "Placilla",
  },
  {
    name: "portezuelo",
    Type: "Commune",
    description: "Portezuelo",
    value: "portezuelo",
    label: "Portezuelo",
  },
  {
    name: "porvenir",
    Type: "Commune",
    description: "Porvenir",
    value: "porvenir",
    label: "Porvenir",
  },
  {
    name: "pozoAlmonte",
    Type: "Commune",
    description: "Pozo Almonte",
    value: "pozoAlmonte",
    label: "Pozo Almonte",
  },
  {
    name: "primavera",
    Type: "Commune",
    description: "Primavera",
    value: "primavera",
    label: "Primavera",
  },
  {
    name: "providencia",
    Type: "Commune",
    description: "Providencia",
    value: "providencia",
    label: "Providencia",
  },
  {
    name: "puchuncavi",
    Type: "Commune",
    description: "Puchuncaví",
    value: "puchuncavi",
    label: "Puchuncaví",
  },
  {
    name: "pucon",
    Type: "Commune",
    description: "Pucón",
    value: "pucon",
    label: "Pucón",
  },
  {
    name: "pudahuel",
    Type: "Commune",
    description: "Pudahuel",
    value: "pudahuel",
    label: "Pudahuel",
  },
  {
    name: "puenteAlto",
    Type: "Commune",
    description: "Puente Alto",
    value: "puenteAlto",
    label: "Puente Alto",
  },
  {
    name: "puertoMontt",
    Type: "Commune",
    description: "Puerto Montt",
    value: "puertoMontt",
    label: "Puerto Montt",
  },
  {
    name: "puertoOctay",
    Type: "Commune",
    description: "Puerto Octay",
    value: "puertoOctay",
    label: "Puerto Octay",
  },
  {
    name: "puertoVaras",
    Type: "Commune",
    description: "Puerto Varas",
    value: "puertoVaras",
    label: "Puerto Varas",
  },
  {
    name: "pumanque",
    Type: "Commune",
    description: "Pumanque",
    value: "pumanque",
    label: "Pumanque",
  },
  {
    name: "punitaqui",
    Type: "Commune",
    description: "Punitaqui",
    value: "punitaqui",
    label: "Punitaqui",
  },
  {
    name: "puntaArenas",
    Type: "Commune",
    description: "Punta Arenas",
    value: "puntaArenas",
    label: "Punta Arenas",
  },
  {
    name: "puqueldon",
    Type: "Commune",
    description: "Puqueldón",
    value: "puqueldon",
    label: "Puqueldón",
  },
  {
    name: "purranque",
    Type: "Commune",
    description: "Purranque",
    value: "purranque",
    label: "Purranque",
  },
  {
    name: "puren",
    Type: "Commune",
    description: "Purén",
    value: "puren",
    label: "Purén",
  },
  {
    name: "putaendo",
    Type: "Commune",
    description: "Putaendo",
    value: "putaendo",
    label: "Putaendo",
  },
  {
    name: "putre",
    Type: "Commune",
    description: "Putre",
    value: "putre",
    label: "Putre",
  },
  {
    name: "puyehue",
    Type: "Commune",
    description: "Puyehue",
    value: "puyehue",
    label: "Puyehue",
  },
  {
    name: "queilen",
    Type: "Commune",
    description: "Queilén",
    value: "queilen",
    label: "Queilén",
  },
  {
    name: "quellon",
    Type: "Commune",
    description: "Quellón",
    value: "quellon",
    label: "Quellón",
  },
  {
    name: "quemchi",
    Type: "Commune",
    description: "Quemchi",
    value: "quemchi",
    label: "Quemchi",
  },
  {
    name: "quilaco",
    Type: "Commune",
    description: "Quilaco",
    value: "quilaco",
    label: "Quilaco",
  },
  {
    name: "quilicura",
    Type: "Commune",
    description: "Quilicura",
    value: "quilicura",
    label: "Quilicura",
  },
  {
    name: "quilleco",
    Type: "Commune",
    description: "Quilleco",
    value: "quilleco",
    label: "Quilleco",
  },
  {
    name: "quillota",
    Type: "Commune",
    description: "Quillota",
    value: "quillota",
    label: "Quillota",
  },
  {
    name: "quillon",
    Type: "Commune",
    description: "Quillón",
    value: "quillon",
    label: "Quillón",
  },
  {
    name: "quilpue",
    Type: "Commune",
    description: "Quilpué",
    value: "quilpue",
    label: "Quilpué",
  },
  {
    name: "quinchao",
    Type: "Commune",
    description: "Quinchao",
    value: "quinchao",
    label: "Quinchao",
  },
  {
    name: "quintadeTilcoco",
    Type: "Commune",
    description: "Quinta De Tilcoco",
    value: "quintadeTilcoco",
    label: "Quinta De Tilcoco",
  },
  {
    name: "quintanormal",
    Type: "Commune",
    description: "Quinta Normal",
    value: "quintanormal",
    label: "Quinta Normal",
  },
  {
    name: "quintero",
    Type: "Commune",
    description: "Quintero",
    value: "quintero",
    label: "Quintero",
  },
  {
    name: "quirihue",
    Type: "Commune",
    description: "Quirihue",
    value: "quirihue",
    label: "Quirihue",
  },
  {
    name: "rancagua",
    Type: "Commune",
    description: "Rancagua",
    value: "rancagua",
    label: "Rancagua",
  },
  {
    name: "ranquil",
    Type: "Commune",
    description: "Ranquil",
    value: "ranquil",
    label: "Ranquil",
  },
  {
    name: "rauco",
    Type: "Commune",
    description: "Rauco",
    value: "rauco",
    label: "Rauco",
  },
  {
    name: "recoleta",
    Type: "Commune",
    description: "Recoleta",
    value: "recoleta",
    label: "Recoleta",
  },
  {
    name: "renaico",
    Type: "Commune",
    description: "Renaico",
    value: "renaico",
    label: "Renaico",
  },
  {
    name: "renca",
    Type: "Commune",
    description: "Renca",
    value: "renca",
    label: "Renca",
  },
  {
    name: "rengo",
    Type: "Commune",
    description: "Rengo",
    value: "rengo",
    label: "Rengo",
  },
  {
    name: "requinoa",
    Type: "Commune",
    description: "Requínoa",
    value: "requinoa",
    label: "Requínoa",
  },
  {
    name: "retiro",
    Type: "Commune",
    description: "Retiro",
    value: "retiro",
    label: "Retiro",
  },
  {
    name: "rinconada",
    Type: "Commune",
    description: "Rinconada",
    value: "rinconada",
    label: "Rinconada",
  },
  {
    name: "rioHurtado",
    Type: "Commune",
    description: "Río Hurtado",
    value: "rioHurtado",
    label: "Río Hurtado",
  },
  {
    name: "romeral",
    Type: "Commune",
    description: "Romeral",
    value: "romeral",
    label: "Romeral",
  },
  {
    name: "rioBueno",
    Type: "Commune",
    description: "Río Bueno",
    value: "rioBueno",
    label: "Río Bueno",
  },
  {
    name: "rioClaro",
    Type: "Commune",
    description: "Río Claro",
    value: "rioClaro",
    label: "Río Claro",
  },
  {
    name: "rioIbanez",
    Type: "Commune",
    description: "Río Ibáñez",
    value: "rioIbanez",
    label: "Río Ibáñez",
  },
  {
    name: "rioNegro",
    Type: "Commune",
    description: "Río Negro",
    value: "rioNegro",
    label: "Río Negro",
  },
  {
    name: "rioVerde",
    Type: "Commune",
    description: "Río Verde",
    value: "rioVerde",
    label: "Río Verde",
  },
  {
    name: "saavedra",
    Type: "Commune",
    description: "Saavedra",
    value: "saavedra",
    label: "Saavedra",
  },
  {
    name: "sagradaFamilia",
    Type: "Commune",
    description: "Sagrada Familia",
    value: "sagradaFamilia",
    label: "Sagrada Familia",
  },
  {
    name: "salamanca",
    Type: "Commune",
    description: "Salamanca",
    value: "salamanca",
    label: "Salamanca",
  },
  {
    name: "sanAntonio",
    Type: "Commune",
    description: "San Antonio",
    value: "sanAntonio",
    label: "San Antonio",
  },
  {
    name: "sanBernardo",
    Type: "Commune",
    description: "San Bernardo",
    value: "sanBernardo",
    label: "San Bernardo",
  },
  {
    name: "sanCarlos",
    Type: "Commune",
    description: "San Carlos",
    value: "sanCarlos",
    label: "San Carlos",
  },
  {
    name: "sanClemente",
    Type: "Commune",
    description: "San Clemente",
    value: "sanClemente",
    label: "San Clemente",
  },
  {
    name: "sanEsteban",
    Type: "Commune",
    description: "San Esteban",
    value: "sanEsteban",
    label: "San Esteban",
  },
  {
    name: "sanFabian",
    Type: "Commune",
    description: "San Fabián",
    value: "sanFabian",
    label: "San Fabián",
  },
  {
    name: "sanFelipe",
    Type: "Commune",
    description: "San Felipe",
    value: "sanFelipe",
    label: "San Felipe",
  },
  {
    name: "sanFernando",
    Type: "Commune",
    description: "San Fernando",
    value: "sanFernando",
    label: "San Fernando",
  },
  {
    name: "sanGregorio",
    Type: "Commune",
    description: "San Gregorio",
    value: "sanGregorio",
    label: "San Gregorio",
  },
  {
    name: "sanIgnacio",
    Type: "Commune",
    description: "San Ignacio",
    value: "sanIgnacio",
    label: "San Ignacio",
  },
  {
    name: "sanJavier",
    Type: "Commune",
    description: "San Javier",
    value: "sanJavier",
    label: "San Javier",
  },
  {
    name: "sanJoaquin",
    Type: "Commune",
    description: "San Joaquín",
    value: "sanJoaquin",
    label: "San Joaquín",
  },
  {
    name: "sanJoseMaipo",
    Type: "Commune",
    description: "San José Maipo",
    value: "sanJoseMaipo",
    label: "San José Maipo",
  },
  {
    name: "sanJuandelacosta",
    Type: "Commune",
    description: "San Juan De La Costa",
    value: "sanJuandelacosta",
    label: "San Juan De La Costa",
  },
  {
    name: "sanMiguel",
    Type: "Commune",
    description: "San Miguel",
    value: "sanMiguel",
    label: "San Miguel",
  },
  {
    name: "sanNicolas",
    Type: "Commune",
    description: "San Nicolás",
    value: "sanNicolas",
    label: "San Nicolás",
  },
  {
    name: "sanPablo",
    Type: "Commune",
    description: "San Pablo",
    value: "sanPablo",
    label: "San Pablo",
  },
  {
    name: "sanPedro",
    Type: "Commune",
    description: "San Pedro",
    value: "sanPedro",
    label: "San Pedro",
  },
  {
    name: "sanPedroAtacama",
    Type: "Commune",
    description: "San Pedro Atacama",
    value: "sanPedroAtacama",
    label: "San Pedro Atacama",
  },
  {
    name: "sanPedrodelapaz",
    Type: "Commune",
    description: "San Pedro De La Paz",
    value: "sanPedrodelapaz",
    label: "San Pedro De La Paz",
  },
  {
    name: "sanRafael",
    Type: "Commune",
    description: "San Rafael",
    value: "sanRafael",
    label: "San Rafael",
  },
  {
    name: "sanRamon",
    Type: "Commune",
    description: "San Ramón",
    value: "sanRamon",
    label: "San Ramón",
  },
  {
    name: "sanRosendo",
    Type: "Commune",
    description: "San Rosendo",
    value: "sanRosendo",
    label: "San Rosendo",
  },
  {
    name: "sanVicente",
    Type: "Commune",
    description: "San Vicente",
    value: "sanVicente",
    label: "San Vicente",
  },
  {
    name: "santaBarbara",
    Type: "Commune",
    description: "Santa Bárbara",
    value: "santaBarbara",
    label: "Santa Bárbara",
  },
  {
    name: "santaCruz",
    Type: "Commune",
    description: "Santa Cruz",
    value: "santaCruz",
    label: "Santa Cruz",
  },
  {
    name: "santaJuana",
    Type: "Commune",
    description: "Santa Juana",
    value: "santaJuana",
    label: "Santa Juana",
  },
  {
    name: "santaMaria",
    Type: "Commune",
    description: "Santa María",
    value: "santaMaria",
    label: "Santa María",
  },
  {
    name: "santiago",
    Type: "Commune",
    description: "Santiago",
    value: "santiago",
    label: "Santiago",
  },
  {
    name: "santiagoNorte",
    Type: "Commune",
    description: "Santiago Norte",
    value: "santiagoNorte",
    label: "Santiago Norte",
  },
  {
    name: "santiagoOeste",
    Type: "Commune",
    description: "Santiago Oeste",
    value: "santiagoOeste",
    label: "Santiago Oeste",
  },
  {
    name: "santiagoSur",
    Type: "Commune",
    description: "Santiago Sur",
    value: "santiagoSur",
    label: "Santiago Sur",
  },
  {
    name: "santoDomingo",
    Type: "Commune",
    description: "Santo Domingo",
    value: "santoDomingo",
    label: "Santo Domingo",
  },
  {
    name: "sierraGorda",
    Type: "Commune",
    description: "Sierra Gorda",
    value: "sierraGorda",
    label: "Sierra Gorda",
  },
  {
    name: "talagante",
    Type: "Commune",
    description: "Talagante",
    value: "talagante",
    label: "Talagante",
  },
  {
    name: "talca",
    Type: "Commune",
    description: "Talca",
    value: "talca",
    label: "Talca",
  },
  {
    name: "talcahuano",
    Type: "Commune",
    description: "Talcahuano",
    value: "talcahuano",
    label: "Talcahuano",
  },
  {
    name: "taltal",
    Type: "Commune",
    description: "Taltal",
    value: "taltal",
    label: "Taltal",
  },
  {
    name: "temuco",
    Type: "Commune",
    description: "Temuco",
    value: "temuco",
    label: "Temuco",
  },
  {
    name: "teno",
    Type: "Commune",
    description: "Teno",
    value: "teno",
    label: "Teno",
  },
  {
    name: "teodoroSchmidt",
    Type: "Commune",
    description: "Teodoro Schmidt",
    value: "teodoroSchmidt",
    label: "Teodoro Schmidt",
  },
  {
    name: "tierraAmarilla",
    Type: "Commune",
    description: "Tierra Amarilla",
    value: "tierraAmarilla",
    label: "Tierra Amarilla",
  },
  {
    name: "tiltil",
    Type: "Commune",
    description: "Tiltil",
    value: "tiltil",
    label: "Tiltil",
  },
  {
    name: "timaukel",
    Type: "Commune",
    description: "Timaukel",
    value: "timaukel",
    label: "Timaukel",
  },
  {
    name: "tirua",
    Type: "Commune",
    description: "Tirúa",
    value: "tirua",
    label: "Tirúa",
  },
  {
    name: "tocopilla",
    Type: "Commune",
    description: "Tocopilla",
    value: "tocopilla",
    label: "Tocopilla",
  },
  {
    name: "tolten",
    Type: "Commune",
    description: "Toltén",
    value: "tolten",
    label: "Toltén",
  },
  {
    name: "tome",
    Type: "Commune",
    description: "Tomé",
    value: "tome",
    label: "Tomé",
  },
  {
    name: "torresdelPaine",
    Type: "Commune",
    description: "Torres Del Paine",
    value: "torresdelPaine",
    label: "Torres Del Paine",
  },
  {
    name: "tortel",
    Type: "Commune",
    description: "Tortel",
    value: "tortel",
    label: "Tortel",
  },
  {
    name: "traiguen",
    Type: "Commune",
    description: "Traiguén",
    value: "traiguen",
    label: "Traiguén",
  },
  {
    name: "treguaco",
    Type: "Commune",
    description: "Treguaco",
    value: "treguaco",
    label: "Treguaco",
  },
  {
    name: "tucapel",
    Type: "Commune",
    description: "Tucapel",
    value: "tucapel",
    label: "Tucapel",
  },
  {
    name: "valdivia",
    Type: "Commune",
    description: "Valdivia",
    value: "valdivia",
    label: "Valdivia",
  },
  {
    name: "vallenar",
    Type: "Commune",
    description: "Vallenar",
    value: "vallenar",
    label: "Vallenar",
  },
  {
    name: "valparaiso",
    Type: "Commune",
    description: "Valparaíso",
    value: "valparaiso",
    label: "Valparaíso",
  },
  {
    name: "vichuquen",
    Type: "Commune",
    description: "Vichuquén",
    value: "vichuquen",
    label: "Vichuquén",
  },
  {
    name: "victoria",
    Type: "Commune",
    description: "Victoria",
    value: "victoria",
    label: "Victoria",
  },
  {
    name: "vicuna",
    Type: "Commune",
    description: "Vicuña",
    value: "vicuna",
    label: "Vicuña",
  },
  {
    name: "vilcun",
    Type: "Commune",
    description: "Vilcún",
    value: "vilcun",
    label: "Vilcún",
  },
  {
    name: "villaAlegre",
    Type: "Commune",
    description: "Villa Alegre",
    value: "villaAlegre",
    label: "Villa Alegre",
  },
  {
    name: "villaAlemana",
    Type: "Commune",
    description: "Villa Alemana",
    value: "villaAlemana",
    label: "Villa Alemana",
  },
  {
    name: "villarrica",
    Type: "Commune",
    description: "Villarrica",
    value: "villarrica",
    label: "Villarrica",
  },
  {
    name: "vitacura",
    Type: "Commune",
    description: "Vitacura",
    value: "vitacura",
    label: "Vitacura",
  },
  {
    name: "vinadelMar",
    Type: "Commune",
    description: "Viña Del Mar",
    value: "vinadelMar",
    label: "Viña Del Mar",
  },
  {
    name: "yerbasBuenas",
    Type: "Commune",
    description: "Yerbas Buenas",
    value: "yerbasBuenas",
    label: "Yerbas Buenas",
  },
  {
    name: "yumbel",
    Type: "Commune",
    description: "Yumbel",
    value: "yumbel",
    label: "Yumbel",
  },
  {
    name: "yungay",
    Type: "Commune",
    description: "Yungay",
    value: "yungay",
    label: "Yungay",
  },
  {
    name: "zapallar",
    Type: "Commune",
    description: "Zapallar",
    value: "zapallar",
    label: "Zapallar",
  },
  {
    name: "niquen",
    Type: "Commune",
    description: "Ñiquén",
    value: "niquen",
    label: "Ñiquén",
  },
  {
    name: "nunoa",
    Type: "Commune",
    description: "Ñuñoa",
    value: "nunoa",
    label: "Ñuñoa",
  },
];

export const auxFiltersConstant = [
  { label: "startDate", value: "" },
  { label: "endDate", value: "" },
  { label: "institutionDestination", value: "all" },
  { label: "clientDni", value: "" },
  { label: "sellerDni", value: "" },
  { label: "debtorDni", value: "" },
  { label: "region", value: "all" },
];
